name: 'e-bot7 core docker image builder'
description: 'Use this action to build and push docker images to ECR'
inputs:
  ecr-repository:
    required: true
    description: name of the ecr namespace
  app-name:
    required: true
    description: name of the app being built
  build-arg:
    required: false
    description: >
      additional build build arguments to be passed when building the dockerfile.
      This should have the form "ARG_NAME=value".
  aws-access-key-id:
    required: true
    description: aws creds to login to ecr repo
  aws-secret-access-key:
    required: true
    description: aws creds to login to ecr repo
  dockerfile-path:
    required: false
    description: The dockerfile path to build from
    default: ./Dockerfile
outputs:
    image_tag: 
        description: Docker tag of image which is based on commit sha
        value: ${{ steps.sha.outputs.sha_short }}
runs:
    using: composite
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create short SHA
        id: sha
        shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build, tag, and push docker image to Amazon ECR
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr-repository }}
          APP_NAME: ${{ inputs.app-name }}
          COMMIT: ${{ steps.sha.outputs.sha_short}}
          BUILDKIT_INLINE_CACHE: 1
          DOCKERFILE_PATH: ${{ inputs.dockerfile-path }}
        run: |
          app_version="${{ github.ref }}-${{ github.run_id }}-$COMMIT"
          build_timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")#
          branch=$(echo ${{ github.ref }} | sed "s/refs\/heads\///g" | sed -r 's/[^-_.a-zA-Z0-9]+/_/g')

          # Pull images to make caching work.
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$branch || docker pull $ECR_REGISTRY/$ECR_REPOSITORY:master || true

          if [ -n '${{ inputs.build-arg }}' ]
          then
            additional_build_arg="--build-arg '${{ inputs.build-arg }}'"
          fi

          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$COMMIT \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$branch \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$APP_NAME-$branch-$COMMIT \
            --cache-from $ECR_REGISTRY/$ECR_REPOSITORY:$branch \
            --cache-from $ECR_REGISTRY/$ECR_REPOSITORY:master \
            --label io.eb7.git_branch="$branch" \
            --label io.eb7.app_version="$app_version" \
            --label io.eb7.service="$APP_NAME" \
            --label io.eb7.log_format=json \
            --label io.eb7.group=application \
            --label org.label-schema.schema-version="1.0.0-rc.1" \
            --label org.label-schema.vendor="e-bot7 GmbH" \
            --label org.label-schema.build-date="$build_timestamp" \
            --label org.label-schema.name="$ECR_REPOSITORY" \
            --label org.label-schema.version="$app_version" \
            --build-arg EB7_APP_VERSION=$app_version \
            -f $DOCKERFILE_PATH \
            $additional_build_arg \
            .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
